spring.application.name=pokemonbackend
spring.datasource.url=jdbc:postgresql://localhost:5432/pokemon_db
spring.datasource.username=postgres
spring.datasource.password=postgres
logging.level.org.springframework.security=DEBUG

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=${PORT:8080}
